# Site info
title: Cholita Linda
description: |-
  Cholita Linda is a chain of street-food restaurants serving fresh foods from exotic ingredients with vibrant colors and the unforgettable taste of Latin America.
cloudinary:
  cloud_name: cholita
  verbose: false
  origin_url: 'https://res.cloudinary.com/cholita/image/upload/'
  presets:
    default:
      min_width: 768
      max_width: 1920
      fallback_max_width: 1280
      steps: 4
image: /images/logo.png
url: 'https://chl.surge.sh'
vcard:
  hours: 'Mon–Sun: 11AM–10PM '
  street: 4923 Telegraph Ave
  phone: '+1 (510) 594-7610'
  email: 'info@cholitalinda.com'
  city: Oakland
  state: CA
  country: Nigeria
social:
  twitter: 'EatCholitaLinda'
  facebook: 'Cholita-Linda-147237876153'
  instagram: 'cholita_linda'

# Data in
font_url: 'https://fonts.googleapis.com/css?family=Cabin:400,500,700|Montserrat:400,500,700,900'

# Build settings
markdown: kramdown
kramdown:
  entity_output: as_char

# Handling Reading
charset: "utf-8"

# Collections
collections:
  images:
    title:  Images
    output: false
  services:
    title: Our Services
    output: false
  recognitions:
    title: Recognitions
    output: false
  our_menus:
    title: Our menu
    description:
    image:
    output: false
  meals:
    title: Cholita Linda Meals
    output: false
  gallery:
    title: Gallery
    output: false

# Defaults
defaults:

# Plugins
plugins:
  - jekyll-menus

# Extraneous folders to include
include:
  - _pages

# Handling Sass
sass:
  sass_dir: _sass
  style: expanded

# Files to exclude on build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '.gitignore'