# Site info
title: Cholita Linda
description: |-
  Cholita Linda is a chain of street-food restaurants serving fresh foods from exotic ingredients with vibrant colors and the unforgettable taste of Latin America.
image: /images/logomark.svg
url: 'https://cholitalinda.com'


# Data in
font_url: 'https://fonts.googleapis.com/css?family=Cabin:400,500,700|Montserrat:400,500,700,900'


# Build settings
markdown: kramdown
kramdown:
  entity_output: as_char


# Handling Reading
charset: "utf-8"


# Handling Sass
sass:
  sass_dir: _sass
  style: compressed


# Collections
collections:
  images:
    title:  Images
    output: false
  recognitions:
    title: Recognitions
    output: false
  our_menus:
    title: Our menu
    description:
    image:
    output: false
  meals:
    title: Cholita Linda Meals
    output: false
  gallery:
    title: Gallery
    output: false
  catering:
    title: Catering
    output: false
  mentions:
    title: mentions
    output: false
  outlets:
    title: Come Visit
    description: Outside of our restaurant, you can find us at many San Francisco Bay Area farmers’ markets and local events.
    call_to_action: Follow us on [Twitter](https://twitter.com/EatCholitaLinda){:target="_blank"} or join us on [Facebook](https://www.facebook.com/pages/Cholita-Linda/147237876153){:target="_blank"} for regular updates.
    output: false


# Defaults
defaults:


# Plugins
plugins:
  - jekyll-menus


# Extraneous folders to include
include:
  - _pages
  - _redirects


# Files to exclude on build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '.gitignore'
