---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _outlets
  label: Outlets (Locations)
  create: all
  match: "**/*"
- type: directory
  path: _mentions
  label: Mentions
  create: all
  match: "**/*"
- type: directory
  path: _gallery
  label: Gallery
  create: all
  match: "**/*"
- type: directory
  path: _meals
  label: Meals
  create: all
  match: "**/*"
- type: directory
  path: _our_menus
  label: Our menus
  create: all
  match: "**/*"
- type: directory
  path: _recognitions
  label: Recognitions
  create: all
  match: "**/*"
- type: document
  path: _data/order_online.yml
  label: Order Online Data
- type: document
  path: _data/business_info.yml
  label: Business Info
- type: document
  path: _pages/about.md
  label: About (Our Story)
upload_dir: _images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
